theme: jekyll-theme-time-machine
title: PhantomFreezer's TechStart Portfolio
description: TechStart Projects

<script src="//360.vizor.io/scripts/embed.js" data-vizorurl="https://360.vizor.io/embed/v/q0vw" ></script>
